import validator from 'validator';
import assert from 'assert';

function testIsAlpha() {
  assert(validator.isAlpha('abcdefg'));
  assert(!validator.isAlpha('abcdefg1'));
  assert(validator.isAlpha('абвгдеёжзийклмнопрстуфхцчшщъыьэюя', 'ru-RU'));
  assert(!validator.isAlpha('абвгдеёжзийклмнопрстуфхцчшщъыьэюя1', 'ru-RU'));
}

function testIsAlphanumeric() {
  assert(validator.isAlphanumeric('abcdefg123'));
  assert(!validator.isAlphanumeric('abcdefg123!'));
  assert(validator.isAlphanumeric('абвгдеёжзийклмнопрстуфхцчшщъыьэюя123', 'ru-RU'));
  assert(!validator.isAlphanumeric('абвгдеёжзийклмнопрстуфхцчшщъыьэюя123!', 'ru-RU'));
}

function testIsEmail() {
  assert(validator.isEmail('foo@bar.com'));
  assert(validator.isEmail('foo.bar@bar.com'));
  assert(validator.isEmail('foo+bar@bar.com'));
  assert(validator.isEmail('foo-bar@bar.com'));
  assert(validator.isEmail('foo@bar.co.uk'));
  assert(validator.isEmail('foo@bar.io'));
  assert(validator.isEmail('foo@bar.museum'));
  assert(validator.isEmail('foo@sub.domain.com'));
  assert(validator.isEmail('123@bar.com'));
  assert(validator.isEmail('test@example.com', { allow_display_name: true }));
  assert(validator.isEmail('"test"@example.com', { allow_display_name: true }));
  assert(validator.isEmail('test <test@example.com>', { allow_display_name: true }));

  assert(!validator.isEmail('foo@bar'));
  assert(!validator.isEmail('foo@'));
  assert(!validator.isEmail('@bar.com'));
  assert(!validator.isEmail('foo'));
  assert(!validator.isEmail('foo@bar.c'));
  assert(!validator.isEmail('foo@bar..com'));
  assert(!validator.isEmail('foo@.bar.com'));
  assert(!validator.isEmail('.foo@bar.com'));
  assert(!validator.isEmail('foo@bar.com.'));
  assert(!validator.isEmail('foo@-bar.com'));
  assert(!validator.isEmail('foo@bar-.com'));
  assert(!validator.isEmail('foo@bar.com-'));
  assert(!validator.isEmail('foo@_bar.com'));
  assert(!validator.isEmail('foo@bar_.com'));
  assert(!validator.isEmail('foo@bar._com'));
}

export function runTest() {
  // Validators
  assert(validator.contains('hello world', 'world'));
  assert(!validator.contains('hello world', 'goodbye'));
  assert(validator.equals('hello', 'hello'));
  assert(!validator.equals('hello', 'world'));
  assert(validator.isAbaRouting('026009593'));
  assert(!validator.isAbaRouting('123456789'));
  assert(validator.isAfter('2025-08-19'));
  assert(!validator.isAfter('2025-08-17'));
  testIsAlpha();
  testIsAlphanumeric();
  assert(validator.isAscii('hello'));
  assert(!validator.isAscii('你好'));
  assert(validator.isBase32('GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ'));
  assert(!validator.isBase32('123'));
  assert(validator.isBase58('123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'));
  assert(!validator.isBase58('1234567890'));
  assert(validator.isBase64('aGVsbG8gd29ybGQ='));
  assert(!validator.isBase64('aGVsbG8gd29ybGQ'));
  assert(validator.isBefore('2025-08-17'));
  assert(!validator.isBefore('2025-08-19'));
  assert(validator.isBIC('SBININBB'));
  assert(!validator.isBIC('SBININB'));
  assert(validator.isBoolean('true'));
  assert(!validator.isBoolean('not a boolean'));
  assert(validator.isBtcAddress('1BoatSLRHtKNngkdXEeobR76b53LETtpyT'));
  assert(!validator.isBtcAddress('not a btc address'));
  assert(validator.isByteLength('hello', { min: 1, max: 10 }));
  assert(!validator.isByteLength('hello world', { min: 1, max: 10 }));
  assert(validator.isCreditCard('4242 4242 4242 4242'));
  assert(!validator.isCreditCard('1234567890123452'));
  assert(validator.isCurrency('1,000.00'));
  assert(!validator.isCurrency('1.000,00'));
  assert(validator.isDataURI('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PjV2VgAAAABJRU5ErkJggg=='));
  assert(!validator.isDataURI('not a data uri'));
  assert(validator.isDate('2025-08-18'));
  assert(!validator.isDate('not a date'));
  assert(validator.isDecimal('1.23'));
  assert(!validator.isDecimal('1,23'));
  assert(validator.isDivisibleBy('10', '2'));
  assert(!validator.isDivisibleBy('10', '3'));
  assert(validator.isEAN('9783161484100'));
  assert(!validator.isEAN('123456789012'));
  testIsEmail();
  assert(validator.isEmpty(''));
  assert(!validator.isEmpty('not empty'));
  assert(validator.isEthereumAddress('0x71c7656ec7ab88b098defb751b7401b5f6d8976f'));
  assert(!validator.isEthereumAddress('0x71c7656ec7ab88b098defb751b7401b5f6d8976'));
  assert(validator.isFloat('1.23'));
  assert(!validator.isFloat('1,23'));
  assert(validator.isFQDN('example.com'));
  assert(!validator.isFQDN('example'));
  assert(validator.isFreightContainerID('MSKU1234565'));
  assert(!validator.isFreightContainerID('MSKU123456'));
  assert(validator.isFullWidth('１２３４５'));
  assert(!validator.isFullWidth('12345'));
  assert(validator.isHalfWidth('12345'));
  assert(!validator.isHalfWidth('１２３４５'));
  assert(validator.isHash('a94a8fe5ccb19ba61c4c0873d391e987982fbbd3', 'sha1'));
  assert(!validator.isHash('a94a8fe5ccb19ba61c4c0873d391e987982fbbd', 'sha1'));
  assert(validator.isHexadecimal('deadbeef'));
  assert(!validator.isHexadecimal('deadbeefg'));
  assert(validator.isHexColor('#ff0000'));
  assert(!validator.isHexColor('#ff000'));
  assert(validator.isHSL('hsl(0, 100%, 50%)'));
  assert(!validator.isHSL('hsl(0, 100, 50)'));
  assert(validator.isIBAN('GB82WEST12345698765432'));
  assert(!validator.isIBAN('GB82WEST1234569876543'));
  assert(validator.isIdentityCard('12345678Z', 'ES'));
  assert(!validator.isIdentityCard('12345678A', 'ES'));
  assert(validator.isIdentityCard('999941057058', 'IN'));
  assert(!validator.isIdentityCard('123456789012', 'IN'));
  assert(validator.isIMEI('356938035643809'));
  assert(!validator.isIMEI('123456789012345'));
  assert(validator.isIn('apple', ['apple', 'banana', 'orange']));
  assert(!validator.isIn('grape', ['apple', 'banana', 'orange']));
  assert(validator.isInt('123'));
  assert(!validator.isInt('1.23'));
  assert(validator.isIP('127.0.0.1'));
  assert(!validator.isIP('127.0.0'));
  assert(validator.isIPRange('192.168.0.1/24'));
  assert(!validator.isIPRange('192.168.0.1'));
  assert(validator.isISBN('978-3-16-148410-0'));
  assert(!validator.isISBN('978-3-16-148410-'));
  assert(validator.isISBN('0-06-112008-1'));
  assert(!validator.isISBN('0-06-112008-'));
  assert(validator.isISIN('US0378331005'));
  assert(!validator.isISIN('US037833100'));
  assert(validator.isISO6346('MSKU1234565'));
  assert(!validator.isISO6346('MSKU123456'));
  assert(validator.isISO6391('en'));
  assert(!validator.isISO6391('eng'));
  assert(validator.isISO8601('2025-08-18T12:00:00.000Z'));
  assert(!validator.isISO8601('not a date'));
  assert(validator.isISO15924('Latn'));
  assert(!validator.isISO15924('Latin'));
  assert(validator.isISO31661Alpha2('US'));
  assert(!validator.isISO31661Alpha2('USA'));
  assert(validator.isISO31661Alpha3('USA'));
  assert(!validator.isISO31661Alpha3('US'));
  assert(validator.isISO31661Numeric('840'));
  assert(!validator.isISO31661Numeric('84'));
  assert(validator.isISO4217('USD'));
  assert(!validator.isISO4217('US'));
  assert(validator.isISRC('USUAN1400011'));
  assert(!validator.isISRC('US-UAN-14-00011'));
  assert(validator.isISSN('2049-3630'));
  assert(!validator.isISSN('2049-363'));
  assert(validator.isJSON('{"foo": "bar"}'));
  assert(!validator.isJSON('{"foo": "bar"'));
  assert(validator.isJWT('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'));
  assert(!validator.isJWT('not a jwt'));
  assert(validator.isLatLong('23.23,23.23'));
  assert(!validator.isLatLong('23.23'));
  assert(validator.isLength('hello', { min: 1, max: 10 }));
  assert(!validator.isLength('hello world', { min: 1, max: 10 }));
  assert(validator.isLicensePlate('B-AB 123', 'de-DE'));
  assert(!validator.isLicensePlate('not a license plate', 'de-DE'));
  assert(validator.isLicensePlate('ABC-123', 'hu-HU'));
  assert(!validator.isLicensePlate('ABC-1234', 'hu-HU'));
  assert(validator.isLocale('en-US'));
  assert(!validator.isLocale('not a locale'));
  assert(validator.isLowercase('hello'));
  assert(!validator.isLowercase('Hello'));
  assert(validator.isLuhnNumber('79927398713'));
  assert(!validator.isLuhnNumber('79927398714'));
  assert(validator.isMACAddress('00:00:00:00:00:00'));
  assert(!validator.isMACAddress('00:00:00:00:00:0'));
  assert(validator.isMagnetURI('magnet:?xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88a&dn=archlinux-2025.08.01-x86_64.iso'));
  assert(!validator.isMagnetURI('magnet:?xt=urn:btih:c12fe1c06bba254a9dc9f519b335aa7c1367a88&dn=archlinux-2025.08.01-x86_64.iso'));
  assert(validator.isMailtoURI('mailto:foo@bar.com'));
  assert(!validator.isMailtoURI('mailto:foo@bar'));
  assert(validator.isMD5('d41d8cd98f00b204e9800998ecf8427e'));
  assert(!validator.isMD5('d41d8cd98f00b204e9800998ecf8427'));
  assert(validator.isMimeType('application/json'));
  assert(!validator.isMimeType('application'));
  assert(validator.isMobilePhone('+15555555555', 'any'));
  assert(!validator.isMobilePhone('+1555555555', 'any'));
  assert(validator.isMobilePhone('+919876543210', 'en-IN'));
  assert(!validator.isMobilePhone('+91987654321', 'en-IN'));
  assert(validator.isMobilePhone('+5511987654321', 'pt-BR'));
  assert(!validator.isMobilePhone('not a mobile phone number', 'pt-BR'));
  assert(validator.isMongoId('507f191e810c19729de860ea'));
  assert(!validator.isMongoId('507f191e810c19729de860e'));
  assert(validator.isMultibyte('你好'));
  assert(!validator.isMultibyte('hello'));
  assert(validator.isNumeric('123'));
  assert(!validator.isNumeric('not a numeric value'));
  assert(validator.isOctal('123'));
  assert(!validator.isOctal('128'));
  assert(validator.isPassportNumber('123456789', 'US'));
  assert(!validator.isPassportNumber('12345678', 'US'));
  assert(validator.isPort('8080'));
  assert(!validator.isPort('80800'));
  assert(validator.isPostalCode('12345', 'US'));
  assert(!validator.isPostalCode('1234', 'US'));
  assert(validator.isPostalCode('A1A 1A1', 'CA'));
  assert(!validator.isPostalCode('A1A 1A', 'CA'));
  assert(validator.isPostalCode('100-0001', 'JP'));
  assert(!validator.isPostalCode('100-000', 'JP'));
  assert(validator.isRFC3339('2025-08-18T12:00:00+00:00'));
  assert(!validator.isRFC3339('2025-08-18T12:00:00'));
  assert(validator.isRgbColor('rgb(255,0,0)'));
  assert(!validator.isRgbColor('rgb(256,0,0)'));
  assert(validator.isSemVer('1.2.3'));
  assert(!validator.isSemVer('1.2'));
  assert(validator.isSurrogatePair('😀'));
  assert(!validator.isSurrogatePair('a'));
  assert(validator.isUppercase('HELLO'));
  assert(!validator.isUppercase('Hello'));
  assert(validator.isSlug('hello-world'));
  assert(!validator.isSlug('hello world'));
  assert(validator.isStrongPassword('Password123!'));
  assert(!validator.isStrongPassword('password'));
  assert(validator.isTime('14:30'));
  assert(!validator.isTime('14:3'));
  assert(validator.isTaxID('123456789', 'en-US'));
  assert(!validator.isTaxID('12345678', 'en-US'));
  assert(validator.isURL('http://example.com'));
  assert(validator.isURL('http://example.com/path'));
  assert(validator.isURL('http://example.com/path/'));
  assert(validator.isURL('http://example.com?foo=bar'));
  assert(validator.isURL('http://example.com?foo=bar&baz=qux'));
  assert(validator.isURL('http://example.com#fragment'));
  assert(validator.isURL('http://example.com/path#fragment'));
  assert(validator.isURL('http://example.com/path?foo=bar'));
  assert(validator.isURL('http://example.com/path?foo=bar#fragment'));
  assert(validator.isURL('https://example.com'));
  assert(validator.isURL('http://example.com:8080'));
  assert(validator.isURL('http://user:pass@example.com'));
  assert(!validator.isURL('not a url'));
  assert(validator.isULID('01F8X3Z2Y6W8T4J0E1N9C2R5A7'));
  assert(!validator.isULID('01F8X3Z2Y6W8T4J0E1N9C2R5A'));
  assert(validator.isUUID('a6a1e7e2-3e4b-4b6e-8b0a-9b0c0d0e0f0a'));
  assert(!validator.isUUID('a6a1e7e2-3e4b-4b6e-8b0a-9b0c0d0e0f0'));
  assert(validator.isVariableWidth('abc１２３'));
  assert(!validator.isVariableWidth('abc'));
  assert(validator.isWhitelisted('hello', 'helo'));
  assert(!validator.isWhitelisted('hello', 'heo'));
  assert(validator.matches('hello', '^[a-z]+$'));
  assert(!validator.matches('hello', '^[A-Z]+$'));

  // Sanitizers
  assert.strictEqual(validator.blacklist('hello world', ' '), 'helloworld');
  assert.strictEqual(validator.escape('<p>hello</p>'), '&lt;p&gt;hello&lt;&#x2F;p&gt;');
  assert.strictEqual(validator.ltrim('  hello'), 'hello');
  assert.strictEqual(validator.normalizeEmail('test@example.com'), 'test@example.com');
  assert.strictEqual(validator.rtrim('hello  '), 'hello');
  assert.strictEqual(validator.stripLow('hello\x00world'), 'helloworld');
  assert.strictEqual(validator.toBoolean('true'), true);
  assert.strictEqual(validator.toDate('2025-08-18').getTime(), new Date('2025-08-18').getTime());
  assert.strictEqual(validator.toFloat('1.23'), 1.23);
  assert.strictEqual(validator.toInt('123'), 123);
  assert.strictEqual(validator.trim('  hello  '), 'hello');
  assert.strictEqual(validator.unescape('&lt;p&gt;hello&lt;/p&gt;'), '<p>hello</p>');
  assert.strictEqual(validator.whitelist('hello world', 'abcdefghijklmnopqrstuvwxyz '), 'hello world');
}
